### PR TITLE
Support `-o` or `--preserve-cell-outputs` to preserve cell outputs

### PR DESCRIPTION
**Pull request by yasirroni**
If you are interested in this ability, I'll help you in the README or others if needed.

### CODE REVIEW

**Comment by yasirroni** [comment]
Solve https://github.com/srstevenson/nb-clean/issues/134

**Review by srstevenson — CHANGES_REQUESTED** [review]
Thanks @yasirroni, this will be a useful addition! The implementation looks good. Can you also add tests in `tests/test_check_notebook.py` and `tests/test_clean_notebook.py`, following how we test the `preserve_cell_metadata` flag, and add documentation to `README.md`? Then I think this'll be ready to merge!

**Comment by yasirroni** [comment]
Test and README updated.

But, `nb-clean check`, `nb-clean add-filter` , and `nb-clean remove-filter`  is not supported yet. I prefer to add that in separate PR.

**Comment by srstevenson** [comment]
I don't know why GitHub has marked this as merged: I squashed your commits and pushed back to this branch, but despite what GitHub is showing this hasn't been merged into `main`. 🤷🏻‍♂️ I've opened #136 with your changes, and as I had some time also implemented the flag for `check` and `add-filter`.

**Pull request merged**
