### PR TITLE
Add support for recursive check/clean

### PR DESCRIPTION
**Pull request by bneijt**
This is a draft implementation of --recursive to show the idea in code and get feedback from the author on willingness to merge a feature like this.

If this is something that the project would merge, a finalizing todo may include:
[ ] Adding unit tests
[ ] Add option to `check` command as well

### CODE REVIEW

**Comment by srstevenson** [comment]
Hi @bneijt -- this is certainly something I'm willing to merge, if you'd like to add the option to the `check` command and some tests. 😃

**Comment by bneijt** [comment]
Added unit test and clean support as well, references https://github.com/srstevenson/nb-clean/issues/147

**Comment by bneijt** [comment]
Please enable the workflow.

One thing to consider is that the current implementation does not enforce a unique set. If you call `nb-clean check -r a a` you will get duplicate files, but this will be the same as getting duplicate files by just calling `nb-clean check a/a.ipynb a/a.ipynb` so I don't think the code should deal with that in a special way.

**Comment by srstevenson** [comment]
@bneijt How about always expanding the arguments that are passed, and removing the `--recursive` flag? This would be consistent with what most Python linters/formatters do (all of mypy, Black, isort, flake8, and pylint recurse into directories by default).

**Comment by bneijt** [comment]
Sounds good to me, I can write that up tomorrow. One thing that you do need to take into account is that clean is a potentiality destructive action that you might not want to recurse automatically. But for check it makes sense.

As you are the maintainer, I leave the choice to you. I'm fine with it, most of my notebook output needs cleaning anyway ;-)

**Comment by yasirroni** [comment]
I hope that this PR supports what I hope exist in this repo, giving a folder and run nb-clean on all notebooks in the directory, see ny failed attempts in https://github.com/srstevenson/nb-clean/pull/150

**Comment by bneijt** [comment]
The last commit makes the recursive action default behavior for both clean and check.

**Review by srstevenson — APPROVED** [review]

**Comment by srstevenson** [comment]
This is now available in [nb-clean 2.3.0](https://pypi.org/project/nb-clean/2.3.0/) on PyPI.

**Pull request merged**
